Misc clippy fixes
zakarumych/egui-probe pull request #9
Opened 2024-12-18 17:19 UTC by xangelix

Just some small clippy fixes to deal with almost all the warnings (at the pedantic level).

Feel free to accept only a portion of this if you don't like the `Self` references for example. I think the rest of the changes look good. :)

2024-12-18 21:15 UTC, zakarumych requested changes
I'm OK with all of it except one instance.

2024-12-18 21:15 UTC, zakarumych commented on src/lib.rs
> +        Self {
I don't like using `Self` in this position.

2024-12-18 22:00 UTC, xangelix commented
Understandable-- done!

I'll go ahead and revert the `Self` references in the value pos for https://github.com/zakarumych/egui-snarl/pull/47 as well.

2024-12-19 10:10 UTC, zakarumych commented
Sorry, I mean in all those places, not just one :)

2024-12-19 10:16 UTC, zakarumych requested changes
And add `![allow(clippy:use_self)]` to the top crate attributes so that it won't trigger the warning if someone runs pedantic clippy.

2024-12-19 10:16 UTC, zakarumych commented on src/map.rs
> +        Self {
Here

2024-12-19 10:16 UTC, zakarumych commented on src/widget.rs
> +        Self {
Here

2024-12-19 10:16 UTC, zakarumych commented on src/widget.rs
> +        Self {
Here

2024-12-19 17:11 UTC, xangelix commented
Sorry about that, definitively not intentional! Looks like some more of my changes didn't go through yesterday as well. I reorganized them into a few different commits.

In particular not so sure about the last two:

- Did you want to use `Self` in pattern matching? Technically this is still under the `clippy::use_self` lint. https://github.com/zakarumych/egui-probe/pull/9/commits/970f881d8bb6772dd2c8b98bcd36590760114890 (would be glad to set allow for the entire proc crate if not)
- Do you care about `clippy::similar_names`? Seems like a dumb change, but I'm happy to change the `_col` wording, or just crate-wide allow that lint as well. https://github.com/zakarumych/egui-probe/pull/9/commits/ce7eaa37700962fa9ae197892dec27fba0bfcaa3

2024-12-19 17:55 UTC, zakarumych commented
Yes, I don't like `clippy::use_self`, and it has lots of issues so was send to "nursery" group.
So I'm not sure why clippy with "pedantic" even uses it

2024-12-19 17:58 UTC, zakarumych commented
As to `fields_col_probe`.
Which name was too similar to `fields_probe`? And what's `col`? Column? Collider? Colon? :)

2024-12-19 18:15 UTC, xangelix commented
> Yes, I don't like `clippy::use_self`, and it has lots of issues so was send to "nursery" group. So I'm not sure why clippy with "pedantic" even uses it

Does that mean you want to keep the pattern matching `Self`s or not?

> As to `fields_col_probe`. What's `col`? Column? Collider? Colon? :)

"Collection"! lol
But honestly whatever is fine. I agree that pendantic has tons of great stuff in there compared to some dumb ones that seem to always come up... eg. complex types, similar names, too many args, use_self kinda iffy too

2024-12-19 20:16 UTC, zakarumych commented
`clippy::use_self` is not in `pedantic` anymore anyway. So whatever changes it brings - please, undo them.

Maybe something like `all_fields_probe` would be less confusing?

2024-12-19 20:27 UTC, xangelix commented
All done.

2024-12-19 21:22 UTC, zakarumych commented
Seems all right!

2024-12-19 21:22 UTC, merged